### ISSUE TITLE
module 'midi' has no attribute 'read_midifile'

### ISSUE THREAD

**Issue by Paras-dua** [llSourcell/Music_Generator_Demo#25]
Traceback (most recent call last):
File "rbm_chords.py", line 36, in 
songs = get_songs('Pop_Music_Midi') # These songs have already been converted from midi to msgpack
File "rbm_chords.py", line 32, in get_songs
raise e
File "rbm_chords.py", line 28, in get_songs
song = np.array(midi_manipulation.midiToNoteStateMatrix(f))
File "C:\Users\Paras\Downloads\tensorflow-music-generator-master\midi_manipulation.py", line 11, in midiToNoteStateMatrix
pattern = midi.read_midifile(midifile)
AttributeError: module 'midi' has no attribute 'read_midifile'
Please provide a solution as soon as possible!

**Comment by ghost** [comment]
I have the same question.... Have you had the solution now?

**Comment by marvinschopf** [comment]
same

**Comment by dewayneroy** [comment]
Has anyone found a solution to this problem? It's really giving me a headache.

**Comment by mehrzeller** [comment]
well : install git first, then reboot your system.
then : pip3 install git+https://github.com/vishnubob/python-midi@feature/python3
should work now

**Comment by EulerGCH** [comment]
Install "module midi" from new repository:
pip install --upgrade git+https:// github.com/louisabraham/python3-midi

**Comment by SuperStar888** [comment]
Is it working now?
