### ISSUE TITLE
msgpack

### ISSUE THREAD

**Issue by johnnogent** [llSourcell/Music_Generator_Demo#4]
Hello

in file rbm_chords.py
_songs = get_songs('Pop_Music_Midi') #These songs have already been converted from midi to msgpack_

How to convert midi to msgpack please?

I have tested this program on my own .mid music. The generated results are 2 seconds each and very fast.

Many thanks to all,
John

**Comment by cgayner** [comment]
Hi there,
I am getting this issue when I run the program:
RESTART: …/Music_Generator_Demo-master/Pop_Music_Midi/rbm_chords_clone.py 

0it [00:00, ?it/s]
0 songs processed

Traceback (most recent call last):
  File "…/Music_Generator_Demo-master/Pop_Music_Midi/rbm_chords_clone.py", line 87, in <module>
    x_sample = gibbs_sample(1)
  File "…/Music_Generator_Demo-master/Pop_Music_Midi/rbm_chords_clone.py", line 77, in gibbs_sample
    [_, _, x_sample] = control_flow_ops.While(lambda count, num_iter, *args: count < num_iter,
AttributeError: 'module' object has no attribute 'While'


--------------------------------
Initially I ran the program as it was but got this error    
…/Music_Generator_Demo-master/Pop_Music_Midi/midi_manipulation.py", line 1, in <module>
import midi
ImportError: No module named midi

I updated the file to read midi_manipulation and it seemed to fix it.

Thought I would mention in case this was wrong.

Welcome thoughts on how to resolve.
Cheers

**Comment by b4zz4** [comment]
I spend me the same.

**Comment by Se7enPhoenix** [comment]
Looks like two people said this. I have the same. What is the solution?

**Comment by K-Kit** [comment]
Could be wrong but i'm fairly sure you just change "file.mid" to "file.midi"
